index.html
script.js

I've initialised the project with an index.html and a script.js and added the initial logic for api calls to the script.js file.
relates to #1

add initial api logic

---

.gitignore
package.json
postmark.js

exports a function that sends email to an array of string email addresses
fix #5

added a postmark module

---

public/script.js
src/routes/apiSendEmail.js
src/routes/home.js
src/routes/index.js
src/utils/postmark.js

we've added a path for callign our postmark that will sed eactual emaisl out! yay! :email: :fire:
fix #19

add path for calling postmark emails

---

public/index.html
public/script.js

Used horrible DOM manipulation to push a list of candidates to a table
fix #21

get a list of candidates onto the dom on submit

---

public/script.js

we've created the form to send emails, and also added state and a set state function so that we can maintian some information through our app
fix #23

create form to send emails

---

emailTemplate.html
src/utils/postmark.js

it now takes an array of recipient objects (name, email) and a sender object (name, email)
relates #31

reformatted postmark.js to send via template

---

public/script.js
src/routes/api.js

we had no error handling for invlaid postcodes so when an invalid req was sent it jsut continually loaded, we now display the error to the user
relates #28

show error on page when postcode invalid

---

public/script.js
src/routes/apiSendEmail.js
src/utils/postmark.js

Add postmark template to front and back ends

---

public/activist-army-styles.css
public/index.html
public/script.js

Added an email template that appears when candidate names are collected
relates #32

email template on front-end

---

public/script.js

we've opted to go for a card based layout rather than a table based layout so changed the code around so we make a card for each candidate rather than a table row
fix #41

Make candidate cards

---

public/activist-army-styles.css
public/script.js

added some nice styles to the candidate cards
relates #35

style cards

---

public/activist-army-styles.css
public/index.html
public/script.js

centered the input forms and made the send emails button a bit more visible
relates #35

added nicer form styling

---

public/activist-army-styles.css
public/script.js

for more of an appy feel the cards change how thhey look when selected
relates #35

make cards look different when selected

---

public/activist-army-styles.css
public/script.js

all of the card is now clickable, it greys out and animates, and the submit button greys out when no candidates are selected. 
relates #35

Card selection

---

public/index.html
public/script.js

The user gets a nice message if any of the emails go through and a nasty error message if they don't.
relates #47

Add email sent / error feedback to dom

---

public/activist-army-styles.css

Changed width to match element below
relates to #35

small fixes to user input form styling

---

src/routes/api.js
src/routes/apiSendEmail.js

Currently it doesn't really do all that much, but definitely better than nothing
relates #27

added initial Joi validation

---

public/script.js

hide email template on email send

---

public/activist-army-styles.css
public/index.html
public/script.js

added instruction to user to select candidates they want to email
relates #9

add instruction to user

---

public/index.html
public/script.js

the user info was showing in the email sent to candidates, but not in the browser, not it is.
relates #9

add username and postcode to form

---

public/index.html
public/script-compiled.js

compile es6 to es5

---

public/activist-army-styles.css

Not display correctly on larger displays

fix banner size on large format displays

---

public/script-compiled.js

add polyfill for Internet Exploder

---

public/script-compiled.js
src/utils/postmark.js

So when users finish reading the template they can send the emails without scrolling up.
Relates #70

Added a second submit email button

---

public/index.html
public/script-compiled.js

if you entered an invalid postcode it would keep on displaying the error forever, not it disappears. Also added html5 email validation to form
fix #77

remove invalid postcode bug

---

public/index.html

i put in a dash when i shouldn't have. oops.
relates #88

change url to correct url

---

public/index.html
public/script-compiled.js

once the user has submitted the initial form the instructions now ceaase to display, as they are no longer needed
also fix #84

Stop displaying instructions

---

public/script-compiled.js

new text: "Please select which candidates you'd like to email."
relates #91

Change the copy for candidate selection
